package com.cs;

public enum LexicalCategory {
    NONE,
    INTEGER_LITERAL,
    STRING_LITERAL,
    CHARACTER_LITERAL,
    FLOATING_POINT_LITERAL,
    IDENTIFIER,
    OPEN_PAREN,
    CLOSE_PAREN,
    SEMICOLON,
    BINARY_ARITHMETIC_OPERATOR,
    BINARY_RELATIONAL_OPERATOR,
    BINARY_LOGICAL_OPERATOR,
    BITWISE_LOGICAL_OPERATOR,
    UNARY_LOGICAL_OPERATOR,
    ASSIGNMENT
}
